config/routes.rb
Bootstrap::Application.routes.draw do
  
  # ROUTES FOR STATIC PAGES
  get '/about' => 'high_voltage/pages#show', id: 'about'
  get '/events' => 'high_voltage/pages#show', id: 'events'
  get '/press' => 'high_voltage/pages#show', id: 'press'
  get '/gallery' => 'high_voltage/pages#show', id: 'gallery'
  get '/privacy' => 'high_voltage/pages#show', id: 'privacy'
  get '/products' => 'high_voltage/pages#show', id: 'products'
  get '/terms' => 'high_voltage/pages#show', id: 'terms'
  get '/tours' => 'high_voltage/pages#show', id: 'tours'
  
  # ROUTES FOR MVC PAGES
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new]
  resources :subscribers, only: [:new, :create]
  
  # Set root using MVC instead of static /home page.
  root to: 'visitors#new'
  
  # REDIRECTS
  # Redirect http://url/home to http://url
  get '/home', to: redirect('/')
  
  #CYA OLD ROUTES
  # Sets root to /home
  # root :to => 'high_voltage/pages#show', id: 'home'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table
  
  column :name, :string
  column :email, :string
  column :content, :string
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email,
    :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
  
  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title("Contact Log")
    if ss.nil?
      ss = connection.create_spreadsheet("Contact Log")
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.now
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end
  
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_no_table
  
  column :name, :string
  column :email, :string
  validates_presence_of :name
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end
  
  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title("Subscriber Log")
    if ss.nil?
      ss = connection.create_spreadsheet("Subscriber Log")
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.now
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws.save
  end

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # This renders /views/contacts/new
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:info] = "Message received from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end  
  
  private
  
  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end
  
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  # This renders /views/subscribers/new
  def new
    @subscriber = Subscriber.new
  end
  
  def create
    @subscriber = Subscriber.new(secure_params)
    if @subscriber.valid?
      @subscriber.update_spreadsheet
      @subscriber.subscribe
      flash[:info] = "#{@subscriber.name}, thanks for subscribing!"
      redirect_to root_path
    else
      render :new
    end
  end
  
  private
  
  def secure_params
    params.require(:subscriber).permit(:name, :email)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def site_name
    "Copper Cannon Distillery"
  end

  def site_url
    if Rails.env.production?
      # Place production URL in quotes below. Will be coppercannondistillery.com once we go live. Also, need to
      # change segment.io URL on that site and add new key to the script in /app/assets/javascripts/segmentio.js
      "http://www.coppercannon.com"
    else
      # Our dev & test URL
      "http://rails-box-68991.use1.nitrousbox.com/"
    end
  end
  
  def meta_author
    "Blake Amacker, K.C. Barrett"
  end
  
  def meta_description
    "Copper Cannon Distillery: Distilling fine spirits in Chesterfield, NH"
  end
  
  def meta_keywords
    "Copper Cannon Distillery, rum, whiskey, micro-distillery, boutique distillery, Chesterfield NH"
  end
  
  # Returns full title on a per-page basis. No need to change any of this as page_title & site_name
  # are set elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end
  
  # Use Bootstrap alert stylings
  def flash_class(level)
    case level
      when :info then "alert alert-info"
      when :success then "alert alert-success"
      when :warning then "alert alert-warning"
      when :danger then "alert alert-danger"
    end        
  end
  
end

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>

<div class="row">
  <div class="col-md-12">
    <h1 class="emphasis">Contact Us</h1>
  </div>
</div>
<div class="row content_top_margin">
  <div class="col-md-12">
    <h3>We'd love to hear from you. Drop us a line and we'll get back to you ASAP!</h3>
  </div>
</div>
<hr>
<div class="form-horizontal" role="form">
  <%= simple_form_for @contact, defaults: { html: { class: 'form-group col-sm-10' } } do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, label: 'Name', placeholder: 'Your name', autofocus: true %>
    <%= form.input :email, label: 'Email', placeholder: '<user@domain.com>' %>
    <%= form.input :content, label: 'Message', placeholder: 'What\'s on your mind?', as: :text %>
    <%= form.button :submit, value: 'Send', class: 'btn btn-primary col-md-offset-2' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <hr>
    <p class="pull-right">
      <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
    </p>
    <p>
      &copy; <%= Time.now.year %> <%= site_name %>
      &bull;
      <%= link_to "Privacy", privacy_path %></li>
      &bull;
      <%= link_to "Terms", terms_path %></li>
    </p>
  </div><!-- /container for footer -->
</footer>

app/views/layouts/_messages.html.erb
<!--<% flash.each do |name, msg| %>
#  <% if msg.is_a?(String) %>
#    <%= content_tag :div, msg, :class => "flash_#{name}" %>
#  <% end %>
#<% end %>-->

<% flash.each do |key, value| %>
  <% if value.is_a?(String) %>
    <div class="<%= flash_class(key) %>">
      <div class="container">
        <%= value %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to site_name, site_url, :class => "navbar-brand" %>
    </div><!-- /.navbar-header -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!-- /.collapse navbar-collapse -->
  </div><!-- /.container -->
</div><!-- /.navbar -->

app/views/layouts/_navigation_links.html.erb
<%# Add navigation links here %>

<li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path %></li>
<li class="<%= 'active' if current_page?(tours_path) %>"><%= link_to "Tours", tours_path %></li>
<li class="<%= 'active' if current_page?(events_path) %>"><%= link_to "Events", events_path %></li>
<li class="<%= 'active' if current_page?(gallery_path) %>"><%= link_to "Gallery", gallery_path %></li>
<li class="<%= 'active' if current_page?(press_path) %>"><%= link_to "Press", press_path %></li>
<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About Us", about_path %></li>
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Contact <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li class="<%= 'active' if current_page?(new_contact_path) %>"><%= link_to "Contact", new_contact_path %></li>
    <li class="<%= 'active' if current_page?(new_subscriber_path) %>"><%= link_to "Subscribe", new_subscriber_path %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <meta charset="utf:8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- [if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body class="background_color">
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </main>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </div><!-- /container for page -->

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>

<div class="row">
  <div class="col-md-12">
    <h1 class="emphasis">About Us</h1>
  </div>
</div>
<hr>
<div class="row content_top_margin">
  <div class="col-md-12">
    <div id="about_background_main">
      <p>
        Two cousins got together one day over drinks and pondered the question, "How do you really make whiskey so good?" 
        Through drinking and dedication to the art of spirits, we came up with a plan to start a distillery. Many 
        nights of experiments and planning have led to the existence of Copper Cannon. We hope you enjoy drinking it as 
          much as we do making it.
      </p>
      <p>
        From your brothers from another mother,
        <br>
        <br>
        <span class="emphasis">– Blake and Chris –</span>
      </p>
    </div>
  </div><!-- col -->
</div><!-- row -->

app/views/pages/events.html.erb
<% provide(:title, 'Events') %>

<div class="row">
  <div class="col-md-12">
    <h1 class="emphasis">Events</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>Planning your next bachelor party, office party, or wake? Copper Cannon Distillery
    is the place for you! - Coming soon!! </h3>
  </div>
</div>
<hr>
<div class="row content_top_margin">
  <div class="col-md-4">
    <h3 class="emphasis">Tastings</h3>
    <%= link_to(image_tag("events/event_1_IMG_0072.png", :alt => "Event", :title => "Event", :class=>"img-rounded gallery_img")) %>
  </div>
  <div class="col-md-4">
    <h3 class="emphasis">Small Party Room</h3>
    <%= link_to(image_tag("events/event_2_IMG_2729.png", :alt => "Event", :title => "Event", :class=>"img-rounded gallery_img")) %>
  </div>
  <div class="col-md-4">
    <h3 class="emphasis">Group Tours</h3>
    <%= link_to(image_tag("events/event_3_IMG_0424.png", :alt => "Event", :title => "Event", :class=>"img-rounded gallery_img")) %>
  </div>
</div>

app/views/pages/gallery.html.erb
<% provide(:title, 'Gallery') %>

<div class="row">
  <div class="col-md-12">
    <h1 class="emphasis">Gallery</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>See what we've been up to!</h3>
  </div>
</div>
<hr>

<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
  <div class="slides"></div>
  <h3 class="title"></h3>
  <a class="prev">‹</a>
  <a class="next">›</a>
  <a class="close">×</a>
  <a class="play-pause"></a>
  <ol class="indicator"></ol>
</div>

<div class="row content_top_margin">
  <div class="col-md-12">
    <div id="links">
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_1_sm_IMG_2451.png", :alt => "R&D still", :title => "R&D still", :class=>"img-rounded"),
            image_path("gallery/gallery_1_lg_IMG_2451.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_2_sm_IMG_2458.png", :alt => "R&D still", :title => "R&D still", :class=>"img-rounded"),
            image_path("gallery/gallery_2_lg_IMG_2458.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_3_sm_IMG_2455.png", :alt => "R&D still", :title => "R&D still", :class=>"img-rounded"),
            image_path("gallery/gallery_3_lg_IMG_2455.png")) %>
        </div>
      </div><!-- /row -->
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_4_sm_IMG_2456.png", :alt => "R&D still", :title => "R&D still", :class=>"img-rounded"),
            image_path("gallery/gallery_4_lg_IMG_2456.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_5_sm_IMG_2729.png", :alt => "R&D still", :title => "R&D still", :class=>"img-rounded"),
            image_path("gallery/gallery_5_lg_IMG_2729.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2737.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2737.png")) %>
        </div>
      </div><!-- /row -->
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2750.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2750.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2746.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2746.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2747.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2747.png")) %>
        </div>
      </div><!-- /row -->
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2753.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2753.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2759.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2759.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2761.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2761.png")) %>
        </div>
      </div><!-- /row -->
      
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2763.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2763.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2767.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2767.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2771.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2771.png")) %>
        </div>
      </div><!-- /row -->
      
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2777.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2777.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2802.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2802.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2803.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2803.png")) %>
        </div>
      </div><!-- /row -->
      
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2804.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2804.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2805.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2805.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2806.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2806.png")) %>
        </div>
      </div><!-- /row -->
      
      <div class="row">
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2810.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2810.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2811.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2811.png")) %>
        </div>
        <div class="col-md-4 gallery_img">
          <%= link_to(image_tag("gallery/gallery_sm_IMG_2820.png", :alt => "Shop", :title => "Shop", :class=>"img-rounded"),
            image_path("gallery/gallery_lg_IMG_2820.png")) %>
        </div>
      </div><!-- /row -->
      
      <script>
        document.getElementById('links').onclick = function (event) {
            event = event || window.event;
            var target = event.target || event.srcElement,
                link = target.src ? target.parentNode : target,
                options = {index: link, event: event},
                links = this.getElementsByTagName('a');
            blueimp.Gallery(links, options);
        };
      </script>
    </div><!-- /links -->
  </div><!-- /column 12-->
</div><!-- /row -->

app/views/pages/home.html.erb
<% provide(:title, '') %>

<% provide(:jumbotron, '
  <h1>Copper Cannon Distillery</h1>
  <small><p>Come get your motha-fuckin\' swerve on at Copper Cannon Distillery! This ain\' yo momma\'s toilet-wine she be makin\' up
in prison, baby; this shit the real deal rightcheer, yaheardme? You think I\'m playin?</p></small>
  <p><a class="btn btn-primary btn-lg" role="button">Activate Swerve &raquo;</a></p>
'.html_safe) %>

<div class="container">
  <div class="row">  
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-4">
          <h2>Past</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
            ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
        <div class="col-md-4">
          <h2>Present</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
            ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
        <div class="col-md-4">
          <h2>Future</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
            ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
      </div><!-- row -->
      <div class="row">
        <div class="col-md-12">
          <h2>Products</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
          ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
          <%= link_to "<button class='btn btn-default' role='button'>View products &raquo;</button>".html_safe, products_path %>
        </div>
      </div><!-- /row -->
    </div><!-- /column-9 -->
    <br/>
    <div class="col-md-3">
      <a class="twitter-timeline" href="https://twitter.com/bogusbarrett" data-widget-id="331417182502256640">Tweets by @bogusbarrett</a>
      <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
        if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      </script>

<!--
      -->
    </div><!-- /column-3 -->
  </div><!-- /row -->  
  
  <hr class="featurette-divider">
  
  <div class="row">
    <div class="col-md-3">
      <h2>Tours</h2>
      <p>We offer tours every Friday starting at 4 PM. Special tours can be arranged too; just send us an email from our 
        <%= link_to "Contact", new_contact_path %> page! Perfect for elementary school field-trips!</p>
      <%= link_to "<button class='btn btn-default' role='button'>View details &raquo;</button>".html_safe, tours_path %>
    </div>
    <div class="col-md-3">
      <h2>Events</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
        ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
      <%= link_to "<button class='btn btn-default' role='button'>View details &raquo;</button>".html_safe, events_path %>
    </div>
    <div class="col-md-3">
      <h2>Friends</h2>
      <p>We'd like to thank the following distilleries for guiding us along the way:</p>
      <ul>
        <li><a href="http://www.copperfox.biz/index" target="blank">Copper Fox Distillery</a></li>
        <li><a href="http://www.flaghill.com" target="blank">Flaghill Distillery</a></li>
        <li><a href="http://www.seahaggdistillery.com" target="blank">Sea Hagg Distillery</a></li> 
      </ul>
    </div>
    <div class="col-md-3">
      <h2>News Updates</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, 
          ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
      <ul>
        <li><a href="#" target="blank">Signing the lease on our building</a></li>
        <li><a href="#" target="blank">Starting construction</a></li>
        <li><a href="#" target="blank">Applying for our TTB permits</a></li>
        <li><a href="#" target="blank">Developing our products</a></li>
        <li><a href="#" target="blank">New products on the way!</a></li>
        <li><a href="#" target="blank">Meet our R&D still</a></li>
      </ul>
    </div><!-- /column -->
  </div><!-- /row -->
</div><!-- /container -->

app/views/pages/press.html.erb
<% provide(:title, 'Press') %>

<div class="row">
  <div class="col-md-12">
    <h1 class="emphasis">Press</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>Here's what they're all saying...</h3>
  </div>
</div>
<hr>
<div class="row content_top_margin">
  <div class="col-md-2"><p>March 22, 2014</p></div>
  <div class="col-md-8"><p>The Battleboro Reformer's coverage of our successful hearing with the Chesterfield 
    Zoning Board of Adjustment.</p>
  </div>
  <div>
    <a class="emphasis col-md-2" href="http://m.reformer.com/brattreformer/db_294474/contentdetail.htm?contentguid=x5OhKRpz&full=true#display" 
       target="blank">Link</a>
  </div>
</div>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy') %>

<h1 class="emphasis">Privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>